# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 358e89bd75e00936294158c9c7322608a12c649167f488ad609a1369d1c0ac43e2a69fcf0bf18f9f9b9292465b680d3e5b37f12598e50b33a1c451a11804609a

test:
  secret_key_base: 2580db58216e7c2d767d8e5871b32882732087699ad8c0d395d05b524781ab0ed2b72b7c845a90069f7d532f691494bdff00b29af9ff342f9eeedc5ffb947ef0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
